---
- name: Install Nginx
  apt: pkg=nginx state=latest

- name: Backup default Nginx config
  command: mv /etc/nginx/nginx.conf /etc/nginx/nginx.conf.default
  args:
    creates: /etc/nginx/nginx.conf.default

- name: Change default nginx config
  template: src=nginx.conf.tpl dest=/etc/nginx/nginx.conf
  notify: restart nginx
